cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name

credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      first_name: John
      last_name: Smith
      password: "123"  # Plain-text password
    rbriggs:
      email: rbriggs@gmail.com
      first_name: Rebecca
      last_name: Briggs
      password: "mypassword"  # Plain-text password
